#!/usr/bin/env python
"""Generate LaTeX macros and table bodies from the saved experiment records.

The report never hard-codes a number.  Every quantity it prints comes from
``results/data/*.json`` through the macros written here, so the prose and the
tables cannot drift away from the data they describe.  Re-run the experiments,
re-run this script, rebuild the PDF: the report follows.

Usage
-----
    python scripts/make_report_macros.py [--results results] [--out docs/report]

Writes
------
``results_generated.tex``
    ``\\newcommand`` definitions for every scalar quoted in the prose.
``table_b_sweep.tex``, ``table_d_threshold.tex``, ``table_e_resources.tex``
    ``tabular`` bodies (rows only) for the three data tables.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

# LaTeX control sequences cannot contain digits, so experiment letters and any
# numeric suffixes are spelled out.
ROMAN = {0: "Zero", 1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six"}


def load(results: Path, name: str) -> dict[str, Any] | None:
    path = results / "data" / f"{name}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def fmt(value: float, places: int = 4) -> str:
    """Fixed-point format, normalising ``-0.0`` so it never prints as ``-0.0000``."""
    if value == 0:
        value = 0.0
    return f"{value:.{places}f}"


def sci(value: float) -> str:
    """Render as LaTeX math in scientific notation, e.g. ``4.33\\times10^{-15}``."""
    if value == 0:
        return "0"
    mantissa, exponent = f"{value:.2e}".split("e")
    return rf"{mantissa}\times10^{{{int(exponent)}}}"


def rate(value: float) -> str:
    """Render an error rate as ``10^{-2}`` when it is a clean power of ten."""
    if value == 0:
        return "0"
    mantissa, exponent = f"{value:.1e}".split("e")
    if mantissa in ("1.0", "1"):
        return rf"10^{{{int(exponent)}}}"
    return rf"{mantissa}\times10^{{{int(exponent)}}}"


def thousands(value: int) -> str:
    return f"{value:,}"


class Macros:
    """Accumulates ``\\newcommand`` definitions."""

    def __init__(self) -> None:
        self.lines: list[str] = []

    def add(self, name: str, value: Any) -> None:
        self.lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

    def section(self, title: str) -> None:
        self.lines.append("")
        self.lines.append(f"% ---- {title} " + "-" * max(0, 60 - len(title)))

    def render(self) -> str:
        header = (
            "% Auto-generated by scripts/make_report_macros.py -- DO NOT EDIT.\n"
            "% Every number in the report comes from results/data/*.json via these\n"
            "% macros, so the prose cannot drift from the data.\n"
        )
        return header + "\n".join(self.lines) + "\n"


def emit_run_metadata(macros: Macros, record: dict[str, Any]) -> None:
    inst = record["instance"]
    env = record.get("environment", {})
    macros.section("run metadata")
    macros.add("RunShots", thousands(record["shots"]))
    macros.add("RunSeed", record["seed"])
    macros.add("RunKeyBits", inst["key_bits"])
    macros.add("RunRounds", inst["rounds"])
    macros.add("RunKeySpace", inst["key_space"])
    macros.add("RunSecretKey", rf"\texttt{{{inst['secret_key_bits']}}}")
    macros.add("RunPairs", inst["num_pairs"])
    macros.add("RunSolutions", inst["num_solutions"])
    macros.add("RunQubits", inst["num_qubits"])
    macros.add("RunKstar", inst["optimal_iterations"])
    macros.add("RunQiskit", env.get("qiskit", "?"))
    macros.add("RunAer", env.get("qiskit_aer", "?"))
    macros.add("RunPython", env.get("python", "?"))


def emit_a(macros: Macros, record: dict[str, Any]) -> None:
    macros.section("Experiment A -- ideal")
    macros.add("AbestK", record["best_iterations"])
    macros.add("AbestP", fmt(record["best_p_success"]))
    macros.add("AdeviationSci", sci(record["max_analytic_deviation"]))
    macros.add("AoverRotation", "yes" if record["over_rotation_observed"] else "no")
    by_k = {row["iterations"]: row for row in record["sweep"]}
    for k, row in by_k.items():
        if k in ROMAN:
            macros.add(f"Aexact{ROMAN[k]}", fmt(row["exact_p_success"]))
    macros.add("AuniformP", fmt(1.0 / record["instance"]["key_space"]))
    macros.add("AmaxK", max(by_k))
    macros.add("Aruntime", fmt(record.get("runtime_seconds", 0.0), 1))


def emit_b(macros: Macros, record: dict[str, Any], out: Path) -> None:
    at = record["at_optimal_iterations"]
    noise = record["noise"]
    macros.section("Experiment B -- noisy")
    macros.add("BpOne", rate(noise["p1"]))
    macros.add("BpTwo", rate(noise["p2"]))
    macros.add("BreadoutZeroOne", f"{noise['p_read_1_given_0']:.0%}".replace("%", r"\%"))
    macros.add("BreadoutOneZero", f"{noise['p_read_0_given_1']:.0%}".replace("%", r"\%"))
    macros.add("Bcx", thousands(at["resources"]["cx"]))
    macros.add("Bdepth", thousands(at["resources"]["depth"]))
    macros.add("BidealP", fmt(at["ideal_p_success"]))
    macros.add("BnoisyP", fmt(at["p_success"]))
    macros.add("BnoisyErr", fmt(at["p_success_stderr"]))
    macros.add("Btvd", fmt(at["tvd_vs_ideal"]))
    macros.add("Bentropy", fmt(at["entropy_bits"], 3))
    macros.add("BentropyMax", fmt(float(record["instance"]["key_bits"]), 3))
    # Older records (written before the two-sigma significance test was added)
    # lack these keys; fall back rather than refusing to build the report.
    if "advantage_sigmas" in record:
        macros.add("Bsigmas", fmt(record["advantage_sigmas"], 1))
    else:
        gap = at["p_success"] - 1.0 / record["instance"]["key_space"]
        err = at["p_success_stderr"] or float("nan")
        macros.add("Bsigmas", fmt(gap / err, 1))
    macros.add("Bsignificant", "yes" if record.get("beats_random_guessing") else "no")
    macros.add("Bruntime", fmt(record.get("runtime_seconds", 0.0), 1))

    rows = []
    for row in record["sweep"]:
        marker = r"\bfseries " if row["iterations"] == record["instance"][
            "optimal_iterations"
        ] else ""
        rows.append(
            f"{marker}{row['iterations']} & {marker}{thousands(row['resources']['cx'])} & "
            f"{marker}{thousands(row['resources']['depth'])} & "
            f"{marker}{fmt(row['ideal_p_success'])} & {marker}{fmt(row['p_success'])} & "
            f"{marker}{fmt(row['tvd_vs_ideal'], 3)} & "
            f"{marker}{fmt(row['entropy_bits'], 3)} \\\\"
        )
    _write(
        out / "table_b_sweep.tex",
        rows,
        colspec="rrrrrrr",
        heading=r"$k$ & CX & Depth & Ideal $P$ & Noisy $P$ & TVD & Entropy",
    )


def emit_c(macros: Macros, record: dict[str, Any]) -> None:
    macros.section("Experiment C -- mitigation")
    macros.add("CidealP", fmt(record["ideal_p_success"]))
    macros.add("Citerations", record["iterations"])
    macros.add("CreducedScale", f"{record.get('reduced_gate_scale', 0):g}")
    macros.add("Cruntime", fmt(record.get("runtime_seconds", 0.0), 1))
    macros.add("CcalibrationCircuits", 1 << record["instance"]["key_bits"])

    labels = {"readout_only": "Readout", "reduced_gate": "Reduced", "full": "Full"}
    for scenario, tag in labels.items():
        data = record["scenarios"].get(scenario)
        if data is None:
            continue
        macros.add(f"C{tag}Raw", fmt(data["raw"]["p_success"]))
        macros.add(f"C{tag}RawTvd", fmt(data["raw"]["tvd_vs_ideal"], 4))
        macros.add(f"C{tag}Fidelity", fmt(data["assignment_matrix"]["mean_readout_fidelity"]))
        macros.add(f"C{tag}Cond", fmt(data["assignment_matrix"]["condition_number"], 2))
        for method in ("pinv", "clip", "nnls"):
            m = data["methods"][method]
            key = f"C{tag}{method.capitalize()}"
            macros.add(f"{key}P", fmt(m["p_success"]))
            macros.add(f"{key}Tvd", fmt(m["tvd_vs_ideal"], 4))
            macros.add(f"{key}Neg", fmt(m["negative_mass"], 4))
            macros.add(f"{key}Valid", "yes" if m["is_valid_distribution"] else "no")
            macros.add(f"{key}Gain", fmt(m["improvement_over_raw"]))


def emit_d(macros: Macros, record: dict[str, Any], out: Path) -> None:
    macros.section("Experiment D -- threshold")
    macros.add("Dcx", thousands(record["resources"]["cx"]))
    macros.add("Ddepth", thousands(record["resources"]["depth"]))
    macros.add("Druntime", fmt(record.get("runtime_seconds", 0.0), 1))
    worst = record["max_working_p2"]
    macros.add("DmaxWorkingPtwo", rate(worst) if worst else "none")
    macros.add("DuniformP", fmt(record["uniform_baseline"]))

    working = [r for r in record["sweep"] if r["top_key_is_solution"] and r["p2"] > 0]
    failing = [r for r in record["sweep"] if not r["top_key_is_solution"]]
    macros.add("DfirstFailingPtwo", rate(failing[0]["p2"]) if failing else "none")
    if working:
        macros.add("DmaxWorkingP", fmt(max(working, key=lambda r: r["p2"])["p_success"]))

    rows = []
    for row in record["sweep"]:
        label = "0 (ideal)" if row["p2"] == 0 else f"${rate(row['p2'])}$"
        rows.append(
            f"{label} & {fmt(row['p_success'])} & {row['rank_of_secret']} & "
            f"{fmt(row['expected_classical_checks'], 1)} & "
            f"{'yes' if row['top_key_is_solution'] else 'no'} \\\\"
        )
    _write(
        out / "table_d_threshold.tex",
        rows,
        colspec="lrrrl",
        heading=(
            r"$p_2$ & $P(\text{key})$ & Rank of key & Checks & Key ranked first"
        ),
    )


def emit_e(macros: Macros, record: dict[str, Any], out: Path) -> None:
    macros.section("Experiment E -- resources")
    rows_data = record["rows"]
    macros.add("Eruntime", fmt(record.get("runtime_seconds", 0.0), 1))
    macros.add("EminKeyBits", min(r["key_bits"] for r in rows_data))
    macros.add("EmaxKeyBits", max(r["key_bits"] for r in rows_data))
    largest = max(rows_data, key=lambda r: r["key_bits"])
    macros.add("EmaxCx", thousands(largest["full_circuit"]["cx"]))
    macros.add("EmaxDepth", thousands(largest["full_circuit"]["depth"]))
    macros.add("EmaxQubits", largest["full_circuit"]["num_qubits"])
    macros.add("EmaxSpeedup", fmt(largest["query_speedup"], 1))
    macros.add("EmaxDensityGB", fmt(largest["density_matrix_bytes"] / 2**30, 1))
    macros.add("EmaxStatevectorMB", fmt(largest["statevector_bytes"] / 2**20, 3))
    smallest = min(rows_data, key=lambda r: r["key_bits"])
    macros.add("EminCx", thousands(smallest["full_circuit"]["cx"]))

    rows = []
    for row in rows_data:
        rows.append(
            f"{row['key_bits']} & {thousands(row['key_space'])} & {row['num_pairs']} & "
            f"{row['full_circuit']['num_qubits']} & {row['grover_iterations']} & "
            f"{thousands(row['full_circuit']['cx'])} & "
            f"{thousands(row['full_circuit']['depth'])} & "
            f"{fmt(row['query_speedup'], 1)}$\\times$ \\\\"
        )
    _write(
        out / "table_e_resources.tex",
        rows,
        colspec="rrrrrrrr",
        heading=(
            r"$n$ & $N$ & Pairs & Qubits & $k^\ast$ & CX & Depth & Query speedup"
        ),
    )


def _write(path: Path, rows: list[str], colspec: str, heading: str) -> None:
    """Write a *complete* ``tabular`` environment to ``path``.

    The whole environment is generated, not just the rows.  ``\\input`` of a
    bare row list from *inside* a ``tabular`` does not work: ``\\input`` is
    unexpandable, so TeX's alignment scanner never sees the following
    ``\\bottomrule``'s ``\\noalign`` in the position it requires, and the build
    fails with "Misplaced \\noalign".  Emitting the environment intact keeps the
    alignment entirely within one file, and has the side benefit of making the
    generated table the single source of truth for its own column layout.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by scripts/make_report_macros.py -- DO NOT EDIT.",
        rf"\begin{{tabular}}{{{colspec}}}",
        r"\toprule",
        heading + r" \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path.name} ({len(rows)} rows)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    root = Path(__file__).resolve().parents[1]
    parser.add_argument("--results", type=Path, default=root / "results")
    parser.add_argument("--out", type=Path, default=root / "docs" / "report")
    args = parser.parse_args(argv)

    macros = Macros()
    records = {
        name: load(args.results, f"experiment_{name}")
        for name in (
            "a_ideal",
            "b_noisy",
            "c_mitigation",
            "d_threshold",
            "e_resources",
        )
    }

    if records["a_ideal"]:
        emit_run_metadata(macros, records["a_ideal"])
        emit_a(macros, records["a_ideal"])
    if records["b_noisy"]:
        emit_b(macros, records["b_noisy"], args.out)
    if records["c_mitigation"]:
        emit_c(macros, records["c_mitigation"])
    if records["d_threshold"]:
        emit_d(macros, records["d_threshold"], args.out)
    if records["e_resources"]:
        emit_e(macros, records["e_resources"], args.out)

    if not any(records.values()):
        print(f"no experiment records found under {args.results / 'data'}")
        return 1

    target = args.out / "results_generated.tex"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(macros.render(), encoding="utf-8")
    count = sum(1 for line in macros.lines if line.startswith(r"\newcommand"))
    print(f"  wrote {target.name} ({count} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
